### PR TITLE
Add virtual environment to the project

### PR DESCRIPTION
**Pull request by StevendeVries**
### What has been done
- Updated composer.lock to updated refs
- Added Vagrantfile to create a virtual/dev environment
- Added Ansible to setup our virtual/dev environment
- Make the daemon run independently of directory
### How to test
- Make sure you have Vagrant, Virtualbox and Ansible installed
- To allow automatic changes to your hostfile als add the vagrant plugin vagrant-hostsupdater

### CODE REVIEW

**Comment by StevendeVries** [comment]
This project aint dead yet :raised_hands: 
!
Up for review :construction_worker: 
@fvdb @rgeraads @aiolos @EliW

**Comment by rgeraads** [comment]
Great work so far!

I tried booting the vagrantbox but I got the following "error":

> TASK [app : Install project dependencies] **************************************
> fatal: [192.168.56.82]: FAILED! => {"changed": true, "cmd": ["composer", "install", "--prefer-dist", "--optimize-autoloader", "--no-interaction"], "delta": "0:00:00.566198", "end": "2016-03-18 19:39:02.211736", "failed": true, "rc": 1, "start": "2016-03-18 19:39:01.645538", "stderr": "Loading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\n  - Removing symfony/config (v2.7.3)\n\n                                                                          \n  [RuntimeException]                                                      \n  The zip extension and unzip command are both missing, skipping.         \n  The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini  \n                                                                          \n\ninstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...", "stdout": "", "stdout_lines": [], "warnings": []}

I ran the command inside the vagrantbox and it gave the following message but continued:

> vagrant@dev:/vagrant$ composer install --prefer-dist --optimize-autoloader
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
>     Failed to download symfony/config from dist: The zip extension and unzip command are both missing, skipping.
> The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
>     Now trying to download from source
> - Installing symfony/config (v2.8.3)
>   Cloning 0f8f94e6a32b5c480024eed5fa5cbd2790d0ad19
>   So that went fine except that provisioning sees the 'failed' as an error.

Also when I tried provisioning a 2nd (and 3rd) time, XDebug raised an error:

> TASK [xdebug : Apply xDebug settings] ******************************************
> failed: [192.168.56.82] => (item={'value': 1, 'key': u'xdebug.remote_autostart'}) => {"failed": true, "item": {"key": "xdebug.remote_autostart", "value": 1}, "msg": "Destination /etc/php/7.0/fpm/conf.d/20-xdebug.ini does not exist !", "rc": 257}
> failed: [192.168.56.82] => (item={'value': u'Phpstorm', 'key': u'xdebug.idekey'}) => {"failed": true, "item": {"key": "xdebug.idekey", "value": "Phpstorm"}, "msg": "Destination /etc/php/7.0/fpm/conf.d/20-xdebug.ini does not exist !", "rc": 257}
> failed: [192.168.56.82] => (item={'value': 1, 'key': u'xdebug.remote_connect_back'}) => {"failed": true, "item": {"key": "xdebug.remote_connect_back", "value": 1}, "msg": "Destination /etc/php/7.0/fpm/conf.d/20-xdebug.ini does not exist !", "rc": 257}
> failed: [192.168.56.82] => (item={'value': 1000, 'key': u'xdebug.max_nesting_level'}) => {"failed": true, "item": {"key": "xdebug.max_nesting_level", "value": 1000}, "msg": "Destination /etc/php/7.0/fpm/conf.d/20-xdebug.ini does not exist !", "rc": 257}
> failed: [192.168.56.82] => (item={'value': 1, 'key': u'xdebug.remote_enable'}) => {"failed": true, "item": {"key": "xdebug.remote_enable", "value": 1}, "msg": "Destination /etc/php/7.0/fpm/conf.d/20-xdebug.ini does not exist !", "rc": 257}

So there needs to be sort of an 'if not exists' there

**Comment by rgeraads** [comment]
ok this is weird.

after destroying the box and reinitializing it worked fine.

However when I do a `composer install` inside the box The error remains.
performing `sudo apt-get install zip` fixes that issue.
Maybe that package should be added to the provisioning.

Apart from that it seems to work!

**Comment by StevendeVries** [comment]
@rgeraads thanks for the feedback. I'll have a look

**Comment by StevendeVries** [comment]
@rgeraads the ziprequirement is just a warning it installs packages fine without it (since it uses download from source instead).

**Pull request merged**
